name: Run Python Script

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '* * * * *'

jobs:
  check_and_cancel:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      run: |
        # Find any runs in progress from the same workflow
        runs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/runs | jq -r '.workflow_runs[] | select(.head_branch == "${{ github.ref }}" and (.status == "in_progress" or .status == "queued" or .status == "waiting")) | .id')

        # Cancel any found runs
        for run in $runs
        do
          echo "Cancelling run: $run"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/runs/$run/cancel
        done


  run-python-script:
    needs: check_and_cancel
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
