name: Run Python Script

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '*/5 * * * *'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if another run is in progress
        id: check
        run: |
          run=$(gh api repos/${{ github.repository }}/actions/runs --paginate | jq -r '.workflow_runs[] | select(.head_branch == "${{ github.ref }}" and .status == "in_progress" and .name == "${{ github.workflow }}") | .id')
          echo "::set-output name=run::$run"

  run-python-script:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.run == ''
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
