name: Run Python Script

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '* * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check for running jobs
      run: |
        # Get the workflow ID
        workflow_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/workflows | jq '.workflows[] | select(.path == ".github/workflows/python_script.yml") | .id')
        
        # Get the raw API response
        response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs)
        
        # Find any runs in progress from the same workflow, excluding the current run
        runs=$(echo "$response" | jq --arg current_run "${{ github.run_id }}" '.workflow_runs[] | select(.head_branch == "${{ github.ref }}" and (.status == "in_progress" or .status == "queued") and .id != $current_run) | .id')

        # If there are other running jobs, exit successfully without running the python script
        if [[ $(echo "$runs" | wc -l) -gt 0 ]]; then
          echo "There are other running jobs. Exiting gracefully..."
          exit 0
        fi

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
